/hcreatelist daemonisch
/haddtolist daemonisch Argfuk Post
/haddtolist daemonisch Argfukqolsmm Postgebaeude,Poststation
/haddtolist daemonisch Armttr Besitz
/haddtolist daemonisch Armtur Besitzer
/haddtolist daemonisch Armturi Besitzerin
/haddtolist daemonisch Arrrr Pirat,Freibeuter
/haddtolist daemonisch Asutur Beschwoerung
/haddtolist daemonisch Asutydel Komponente
/haddtolist daemonisch Bhuturih Frau,Schlampe,Weib
/haddtolist daemonisch Blem Ei
/haddtolist daemonisch Blemziihp Kleriker,Weichei
/haddtolist daemonisch Bonk Boing
/haddtolist daemonisch Bruchasut Pentagramm
/haddtolist daemonisch Bruchk Daemon,Daemons, Daemones
/haddtolist daemonisch Bruchoknik Bannkreis
/haddtolist daemonisch Bumlegmdowe Helmchen
/haddtolist daemonisch Bumlekaspartar Herrchen
/haddtolist daemonisch Bumlekroeter Huendchen
/haddtolist daemonisch Bumlesufzk Bierchen
/haddtolist daemonisch Bumlevitar Moment,Moments
/haddtolist daemonisch Bumleymdel Haendchen
/haddtolist daemonisch Bumleymdelchen Fingerchen
/haddtolist daemonisch Chaoloe Gut
/haddtolist daemonisch Chaoloeydel Hilfe
/haddtolist daemonisch Cutralk Betretung
/haddtolist daemonisch Dhyx Naehe
/haddtolist daemonisch Ex Ende
/haddtolist daemonisch Frumpf Essen
/haddtolist daemonisch Frumx Zahn
/haddtolist daemonisch Fruual Wasser
/haddtolist daemonisch Fsup Ruhe
/haddtolist daemonisch Ghmle Bestie,Beute,Tier
/haddtolist daemonisch Ghmlesn Jagd,Jagden,Jagens
/haddtolist daemonisch Gmdemh Schild,Schildes
/haddtolist daemonisch Gmdler Ruestung
/haddtolist daemonisch Gmdowe Helm
/haddtolist daemonisch Gmurs Burg
/haddtolist daemonisch Grrumtsacol Tag
/haddtolist daemonisch Grrumywairn Gefangenschaft
/haddtolist daemonisch Grumm Abwesenheit
/haddtolist daemonisch Hrumtels Zwerg
/haddtolist daemonisch Hsunge Wissen
/haddtolist daemonisch Humrm Portal
/haddtolist daemonisch Inarkzzrusta Eingeweide
/haddtolist daemonisch Jepjep Jof
/haddtolist daemonisch Juuumz Rumata
/haddtolist daemonisch Kaspar Herres,Herrens
/haddtolist daemonisch Kaspartar Herrscher,Koenig
/haddtolist daemonisch Kauz Sau,Schwein
/haddtolist daemonisch Klumslrm Untergebener
/haddtolist daemonisch Klumslsm Diener
/haddtolist daemonisch Klumsltm Sklave
/haddtolist daemonisch Knarrzz Baum,Baeume,Holz
/haddtolist daemonisch Kroeter Hund
/haddtolist daemonisch Kroeterwirmk Katze
/haddtolist daemonisch Kroszbruchk Chaosdaemon
/haddtolist daemonisch Krotzlikvacuhm Dummkopf
/haddtolist daemonisch Kroxx Chaot
/haddtolist daemonisch Krozx Chaos
/haddtolist daemonisch Lumkroz Anflehen,Anflehung
/haddtolist daemonisch Lyheart Mann
/haddtolist daemonisch Malitrr Feuer
/haddtolist daemonisch Malitrramoerl Feueraxt
/haddtolist daemonisch Malitrrpornskinarkfruual Feuerinsel
/haddtolist daemonisch Malitrrwirmk Feuerwehr
/haddtolist daemonisch Manok Hoelle
/haddtolist daemonisch Manor Tod
/haddtolist daemonisch Manorm sterben
/haddtolist daemonisch Manorzulsch Todesfalle
/haddtolist daemonisch Manqurs Pest
/haddtolist daemonisch Mdem List
/haddtolist daemonisch Motz Bild,Bildnis,Photo
/haddtolist daemonisch Mtshh Gewicht
/haddtolist daemonisch Myamm Schleim
/haddtolist daemonisch Namakri Farbe
/haddtolist daemonisch Nyrksooltesh Aengstlichkeit,Angst,
/haddtolist daemonisch Oelkurs Elf
/haddtolist daemonisch Oermksbhuturih Maedchen
/haddtolist daemonisch Oermkslyheart Junge
/haddtolist daemonisch Oknik Kreis
/haddtolist daemonisch Onrurlas Transport
/haddtolist daemonisch Oolms Feigheit
/haddtolist daemonisch Ooltesh Mut
/haddtolist daemonisch Pahhzzrusta Haut
/haddtolist daemonisch Pfuivmoepouel Kaempfer
/haddtolist daemonisch Pllmdem Hinterlist
/haddtolist daemonisch Pornsk Raum
/haddtolist daemonisch Pornskinarkfruual Insel
/haddtolist daemonisch Pusf Wut
/haddtolist daemonisch Qolsarm Hoehle
/haddtolist daemonisch Qolsmm Haus
/haddtolist daemonisch Qulasar Groesse
/haddtolist daemonisch Qulasarzulsch Gefahr
/haddtolist daemonisch Quralsch Drache
/haddtolist daemonisch Ramtalq Eis
/haddtolist daemonisch Risstars Mensch
/haddtolist daemonisch Romtschprrem Friedhof
/haddtolist daemonisch Romtzz Laute
/haddtolist daemonisch Ronam Leben
/haddtolist daemonisch Rontk Hebel
/haddtolist daemonisch Rutusa Bann,Bannzauber
/haddtolist daemonisch Sameln Schwert
/haddtolist daemonisch Samklerl Waffe
/haddtolist daemonisch Samoerl Axt
/haddtolist daemonisch Samor Ecke,Ecken
/haddtolist daemonisch Samorr Riss
/haddtolist daemonisch Samorx Nadel
/haddtolist daemonisch Samower Messer
/haddtolist daemonisch Sarrss Satan,Satanas,Teufel
/haddtolist daemonisch Schhhi Wind
/haddtolist daemonisch Schrecken
/haddtolist daemonisch Shirz Beschaeftigung
/haddtolist daemonisch Shot Lied
/haddtolist daemonisch Sorrss Gott
/haddtolist daemonisch Spooz Schuh,Stiefel
/haddtolist daemonisch Strunz Macht
/haddtolist daemonisch Strunz! Machtvolle,
/haddtolist daemonisch Sufzk Bier
/haddtolist daemonisch Sufzkmoerksl Gefaess
/haddtolist daemonisch Tralk Fuss,Fuesse,Tritt
/haddtolist daemonisch Tramslm Sprache
/haddtolist daemonisch Trtweslmachx Krieg
/haddtolist daemonisch Tsacol Nacht
/haddtolist daemonisch Tsacolschhhiz Nachtwind
/haddtolist daemonisch Ubelrs Schwefel
/haddtolist daemonisch Uiurksbumleummsl Faden
/haddtolist daemonisch Uiurksbumleyluars Dorf,Siedlung
/haddtolist daemonisch Uiurksvacuhm Koepfchen
/haddtolist daemonisch Uiurkswesltam Grausamkeit
/haddtolist daemonisch Ummsl Seil
/haddtolist daemonisch Ummwl Schlaufe
/haddtolist daemonisch Urksvitar Spaet,spaeter, spaetestens
/haddtolist daemonisch Uurksknarrzz Wald
/haddtolist daemonisch Uurksknarrzzmanorm Waldsterben
/haddtolist daemonisch Uurksuiurksvitar Zukunft
/haddtolist daemonisch Uurkswesltam Hass
/haddtolist daemonisch Vacuhm Kopf
/haddtolist daemonisch Vmoepouel Kampf,Krieger,Metzler
/haddtolist daemonisch Vmoewqld Mord
/haddtolist daemonisch Weselmu Gift
/haddtolist daemonisch Wirmk Feind
/haddtolist daemonisch Wrijlksod Gruss,Gruesse
/haddtolist daemonisch Xarmst Freund
/haddtolist daemonisch Xohhz Wille
/haddtolist daemonisch Xohhzhsunge Frage
/haddtolist daemonisch Xorchm Gabe,Geschenk
/haddtolist daemonisch Xurns Verraeter
/haddtolist daemonisch Xurnszf Verrat
/haddtolist daemonisch Xxmrem Gemeinheit
/haddtolist daemonisch Xxmremz Gemeinheiten
/haddtolist daemonisch Xyhd Ferne
/haddtolist daemonisch Ydel Herstellung
/haddtolist daemonisch Yluars Stadt
/haddtolist daemonisch Ymdel Hand
/haddtolist daemonisch Ymdelchen Finger
/haddtolist daemonisch Ymdelkmera Kralle
/haddtolist daemonisch Ymdelkmerm Krallen
/haddtolist daemonisch Ymdelspooz Handschuh
/haddtolist daemonisch Ywairn Freiheit
/haddtolist daemonisch Zak Auge,Augen
/haddtolist daemonisch Zirlsch Grube
/haddtolist daemonisch Zllmoer Knopf
/haddtolist daemonisch Zllssr Schalter
/haddtolist daemonisch Zrlulur Arbeit
/haddtolist daemonisch Zrlulurbhuturih Arbeiterin
/haddtolist daemonisch Zrlulurlyheart Arbeiter
/haddtolist daemonisch Zulisch Sturz
/haddtolist daemonisch Zulsch Falle
/haddtolist daemonisch Zulschzirlsch Fallgrube
/haddtolist daemonisch Zurlism Tor,Tuer
/haddtolist daemonisch Zzep Arm
/haddtolist daemonisch Zzrusta Koerper
/haddtolist daemonisch ambu schwarz
/haddtolist daemonisch armttr besitzen,besitzend,
/haddtolist daemonisch asutur beschwoeren,beschwoerend
/haddtolist daemonisch baygh holen
/haddtolist daemonisch bhuturih weiblich
/haddtolist daemonisch bimula ausmachen,loeschen
/haddtolist daemonisch bmlel wem,wessen
/haddtolist daemonisch boumf so,echt,wahr
/haddtolist daemonisch bruchtka daemonisch
/haddtolist daemonisch bumle klein
/haddtolist daemonisch bumlevitar momentan,nun,sofort,jetzt
/haddtolist daemonisch chaola schnell
/haddtolist daemonisch chaoloe gut,gute,guten
/haddtolist daemonisch chaoputm langsam
/haddtolist daemonisch crant dein,deine
/haddtolist daemonisch cutralk betreten
/haddtolist daemonisch dhyx nah
/haddtolist daemonisch drukck morgen
/haddtolist daemonisch ek auch,wie
/haddtolist daemonisch enbkema schliessen
/haddtolist daemonisch erdasu bekommen,bekommst
/haddtolist daemonisch exa ende,enden,Endes
/haddtolist daemonisch frumpf essen
/haddtolist daemonisch frumtlx heut,heute
/haddtolist daemonisch fruual waessrig
/haddtolist daemonisch fsup ruhig
/haddtolist daemonisch garut zehn
/haddtolist daemonisch gmdler schuetzen
/haddtolist daemonisch grrum abwesend,fort,nicht
/haddtolist daemonisch grrumchaoloe schlecht
/haddtolist daemonisch grrummtshh leicht
/haddtolist daemonisch grrumrisstars unmenschlich
/haddtolist daemonisch grrumtrtinark leer
/haddtolist daemonisch grrumtrtinarkydel ausnehmen
/haddtolist daemonisch grrumtsacol taeglich
/haddtolist daemonisch grrumywairn gefangen
/haddtolist daemonisch grruz nie
/haddtolist daemonisch haben
/haddtolist daemonisch har ja
/haddtolist daemonisch harus bin,bist,sein,seist,sind
/haddtolist daemonisch hoech sauber
/haddtolist daemonisch hoechhoech putzen
/haddtolist daemonisch hohowuz wuscheln
/haddtolist daemonisch hsunge wissen
/haddtolist daemonisch huwn zwei
/haddtolist daemonisch hux alt
/haddtolist daemonisch iamti zu,zur,zum
/haddtolist daemonisch inark im,in,ins
/haddtolist daemonisch irimtus finden
/haddtolist daemonisch itram rot
/haddtolist daemonisch jahueb sieben
/haddtolist daemonisch jornt eins
/haddtolist daemonisch kaspartar herrschen
/haddtolist daemonisch kauz schweinisch
/haddtolist daemonisch klumsl untergeben
/haddtolist daemonisch knarrzz hoelzern
/haddtolist daemonisch kra zu,zum,zur
/haddtolist daemonisch krant euer,eure,mein,meine,
/haddtolist daemonisch krotzlik doof
/haddtolist daemonisch krozx chaotisch,chaotischst
/haddtolist daemonisch krunk vor,vor-,bei-
/haddtolist daemonisch krx aus,heraus
/haddtolist daemonisch loemuq oeffne,oeffnen,offen
/haddtolist daemonisch lumkroz anflehen,flehen
/haddtolist daemonisch lumsloq dienen,gehorchen
/haddtolist daemonisch lumuar gestern
/haddtolist daemonisch luqosm ergib,ergebene
/haddtolist daemonisch lyheart maennlich
/haddtolist daemonisch lysim neun
/haddtolist daemonisch malitrr feurig
/haddtolist daemonisch maxkra zuviel
/haddtolist daemonisch mdem listig
/haddtolist daemonisch mesiry blau
/haddtolist daemonisch moerks legen
/haddtolist daemonisch moerkskal mit,mittels
/haddtolist daemonisch moerksl in,ins,mit
/haddtolist daemonisch moerksn liegen
/haddtolist daemonisch mtshh schwer
/haddtolist daemonisch murms der,die,das
/haddtolist daemonisch myamm schleimig,verschleimt
/haddtolist daemonisch myp er,es,sie
/haddtolist daemonisch nagam gelb
/haddtolist daemonisch namakri farbig
/haddtolist daemonisch natar norden
/haddtolist daemonisch nok von,vom
/haddtolist daemonisch nurms die,dem,den,des, dessen
/haddtolist daemonisch nurns dem,die,den,des
/haddtolist daemonisch nyrks etwas,kein,keine,wenig,ohne
/haddtolist daemonisch nyrksooltesh aengstlich, schrecklich
/haddtolist daemonisch nyrkszulsch gefahrlos,harmlos
/haddtolist daemonisch oatar osten,oestlich
/haddtolist daemonisch oermks fast
/haddtolist daemonisch oermksambu grau
/haddtolist daemonisch oermkskrotzlik duemmlich,dumm
/haddtolist daemonisch oermksvitar gleich
/haddtolist daemonisch ohoh dies,diese,jene, jenes,welche,welches
/haddtolist daemonisch ohohpornsk hier,hierher,hierhin
/haddtolist daemonisch ohohpronks dort,dorther,dorthin
/haddtolist daemonisch oknik rund
/haddtolist daemonisch oolms feige
/haddtolist daemonisch ooltesh mutig
/haddtolist daemonisch ox ab
/haddtolist daemonisch pahh an,am,bei
/haddtolist daemonisch pahhzzrusta nackt
/haddtolist daemonisch pfuck ich,man,selbst
/haddtolist daemonisch phiiz hart
/haddtolist daemonisch pimrt acht
/haddtolist daemonisch pllmda hinterlistig
/haddtolist daemonisch pollm wie
/haddtolist daemonisch pollmms wieso,weshalb,warum
/haddtolist daemonisch psiwqrx jetzt,sofort
/haddtolist daemonisch pusf wuetend
/haddtolist daemonisch qulasar gross
/haddtolist daemonisch qulasarzulsch gefaehrlich
/haddtolist daemonisch ramtalq eisig
/haddtolist daemonisch rkx herum,um
/haddtolist daemonisch romtsch leise(s),ruhe(n),ruht,still,Stille
/haddtolist daemonisch romtz laut
/haddtolist daemonisch ronam leben
/haddtolist daemonisch rrum gegen
/haddtolist daemonisch rtt fuer,wegen
/haddtolist daemonisch rufurt gruen
/haddtolist daemonisch rummelmupf arm
/haddtolist daemonisch runzelbrum komm,komme,kommt,kommst
/haddtolist daemonisch rutusa bannen,verbannen
/haddtolist daemonisch sabbre gern,gerne
/haddtolist daemonisch samor eck,eckig
/haddtolist daemonisch samorr reissen
/haddtolist daemonisch samorx spitz
/haddtolist daemonisch samorxm stechen
/haddtolist daemonisch satar noerdlich,suedlich,sueden
/haddtolist daemonisch schhhi windig
/haddtolist daemonisch shiffz pinkeln
/haddtolist daemonisch shirz beschaeftigen, beschaeftigend
/haddtolist daemonisch shockl sing,singen,singend
/haddtolist daemonisch shockllsl schreien,schreiend
/haddtolist daemonisch sorrss goettlich
/haddtolist daemonisch stoeckm geh,gehe
/haddtolist daemonisch strunz maechtig
/haddtolist daemonisch sufzzz trink,trinken,trinkt
/haddtolist daemonisch tramsllwl rede,reden
/haddtolist daemonisch tramslm sag,sagen,sagte, sprich,sprechen
/haddtolist daemonisch tramslsl sprechen
/haddtolist daemonisch tramslslsl ruf,rufen,ruft
/haddtolist daemonisch trookasr neu,neues
/haddtolist daemonisch troomt nerven
/haddtolist daemonisch trt alle(s),allerlei,jede(m),viel,vieles
/haddtolist daemonisch trtinark voll
/haddtolist daemonisch trueyk test,teste,Tester
/haddtolist daemonisch trxu ist
/haddtolist daemonisch tsacol nachts
/haddtolist daemonisch tzmus ob,wenn,wann
/haddtolist daemonisch uemsgrrl naechste,naechster,naechstes
/haddtolist daemonisch uemsguel nach,nachdem
/haddtolist daemonisch uenkl ein,eine,einer,eines
/haddtolist daemonisch uiurks extrem
/haddtolist daemonisch uiurksbumle winzig
/haddtolist daemonisch uiurkskrotzlik bescheuert
/haddtolist daemonisch uiurksqulasar groesser
/haddtolist daemonisch uiurksstoeckm rennen,renne
/haddtolist daemonisch uiurkstrt ausschliesslich,nur
/haddtolist daemonisch uiurkswesltam grausam
/haddtolist daemonisch unar koennen
/haddtolist daemonisch unser,unsere,deine
/haddtolist daemonisch urhoech weiss
/haddtolist daemonisch uurks sehr
/haddtolist daemonisch uurksgrruz niemals,noch
/haddtolist daemonisch uurksknarrzz bewaldet
/haddtolist daemonisch uurkskrotzlik verdammt,bloed
/haddtolist daemonisch uurksstoeckm lauf,laufen
/haddtolist daemonisch uurksuiurksvitar zukuenftig
/haddtolist daemonisch uurkswesltam hassen
/haddtolist daemonisch vitar zeit
/haddtolist daemonisch vitarl zeitig,zeitlich
/haddtolist daemonisch vmoepouel kaempf,kaempfen, metzeln,nerven,nervig
/haddtolist daemonisch vmoequel toeten
/haddtolist daemonisch vmoetuzz suchen
/haddtolist daemonisch vmoewole hau,hauen
/haddtolist daemonisch vmoewqld morde,morden
/haddtolist daemonisch vmoeyxmel jagen
/haddtolist daemonisch watar westen,westlich
/haddtolist daemonisch weselmsj giftig
/haddtolist daemonisch weselmteml tueckisch, heimtueckisch
/haddtolist daemonisch weslmachx toete,toeten
/haddtolist daemonisch weslmge toedlich
/haddtolist daemonisch wesltam gemein
/haddtolist daemonisch wit was
/haddtolist daemonisch wnyir fuenf
/haddtolist daemonisch xarmst freundlich
/haddtolist daemonisch xkr auf,herauf
/haddtolist daemonisch xohhz wollen,sollen,muessen
/haddtolist daemonisch xohhzhsunge fragen
/haddtolist daemonisch xorchm geb,geben,gib, schenke,verschenke
/haddtolist daemonisch xrk herein,rein
/haddtolist daemonisch xron genauso
/haddtolist daemonisch xrox aber,oder,und,doch
/haddtolist daemonisch xuh jung,neu
/haddtolist daemonisch xurnszf verraten
/haddtolist daemonisch xuzsiik besonders
/haddtolist daemonisch xyhd fern
/haddtolist daemonisch ydel mach,machen,tun
/haddtolist daemonisch ydeltrtinark fuellen
/haddtolist daemonisch yfhozz benoetigen,brauchen
/haddtolist daemonisch ymurt sechs
/haddtolist daemonisch yorchm nimm,nehmen
/haddtolist daemonisch yque dich,dir,du,mein,mich,mir,wir
/haddtolist daemonisch ywairn frei
/haddtolist daemonisch ywops drei
/haddtolist daemonisch zak (an)schauen,(an)sehen,betrachten
/haddtolist daemonisch zakzulsch aufpassen
/haddtolist daemonisch ziihp weich
/haddtolist daemonisch zlah als
/haddtolist daemonisch zrlulur arbeiten
/haddtolist daemonisch zulisch fallen,stuerzen
/haddtolist daemonisch zyrim vier
/haddtolist daemonisch zzak anschaulich
/haddtolist daemonisch zzaksn malen,zeichnen
/haddtolist daemonisch zzrusta koerperlich

/def dparse = \
        /let param=%*%;\
    	  /test tokenize(" ",param)%;\
	  /let tcount=0%;\
	  /set dparse=%;\
          /let dparseoutput=Uebersetzung:%;\
	  /while (++tcount<=T0) \
	     /test dparse:=\{T%{tcount}\}%;\
             /set dparselen=0%;\
             /set dparseres=%dparse%;\
             /hforEach daemonisch kv /dparse2%;\
             /let dparseoutput=%dparseoutput  %dparseres%;\
	  /done%;\
          /echo %dparseoutput%;

/def dparse2 = \
      /if (dparse=/strcat({1},"*") & dparselen<strlen({1})) \
        /test dparselen:=strlen({1})%;\
        /set dparseres=%{-1}%;\
      /endif%;

